version: '3.8'

services:
  # Base de datos MongoDB
  mongodb:
    image: mongo:4.4.18
    container_name: counter_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: counterapp
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - counter-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: counter_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/counterapp?authSource=admin
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - counter-network

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: counter_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - counter-network

volumes:
  mongodb_data:

networks:
  counter-network:
    driver: bridge
